# Generated by Django 6.0.1 on 2026-01-29 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_name'),
        ('master_management', '0010_merge_20260128_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.masterlogintype'),
        ),
    ]
