# Generated by Django 6.0.1 on 2026-01-29 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_product_service', '0001_initial'),
        ('sub_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproductservice',
            name='sub_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_services', to='sub_client.subclient'),
        ),
    ]
