# Generated by Django 6.0.1 on 2026-01-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_product_service', '0002_clientproductservice_sub_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientproductservice',
            name='sub_client',
        ),
    ]
