# Generated by Django 6.0.1 on 2026-02-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careprogramcase',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='careprogramcase',
            name='customer_dependent',
        ),
        migrations.AddField(
            model_name='careprogramcase',
            name='customer_name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
