# Generated by Django 6.0.1 on 2026-02-03 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_programs', '0002_remove_careprogramcase_customer_and_more'),
        ('client_customer', '0008_alter_clientcustomer_employee_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careprogramcase',
            name='relationship_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='care_cases', to='client_customer.clientcustomerdependent'),
        ),
    ]
