# Generated by Django 6.0.1 on 2026-01-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_branch', '0002_clientbranch_login_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientbranch',
            name='login_type',
        ),
    ]
