# Generated by Django 5.2.7 on 2026-01-23 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalMedicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('case_entry_datetime', models.DateTimeField()),
                ('case_received_mode', models.CharField(max_length=50)),
                ('case_received_datetime', models.DateTimeField()),
                ('welleazy_branch', models.CharField(max_length=100)),
                ('assigned_executive', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalMedicalCaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_test', models.CharField(max_length=255)),
                ('welleazy_generic_test', models.CharField(max_length=255)),
                ('customer_profile', models.CharField(max_length=50)),
                ('customer_pay_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('application_no', models.CharField(max_length=50)),
                ('case_type', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=50)),
                ('case_for', models.CharField(max_length=50)),
                ('dhoc_advance_payment', models.CharField(max_length=10)),
                ('preferred_visit_type', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_appointment_datetime', models.DateTimeField(blank=True, null=True)),
                ('case_status', models.CharField(default='Fresh Case', max_length=50)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_detail', to='physical_medicals.physicalmedicalcase')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalMedicalClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('branch_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_name', models.CharField(max_length=100)),
                ('customer_type', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('services_offered', models.CharField(max_length=255)),
                ('received_by', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_detail', to='physical_medicals.physicalmedicalcase')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalMedicalCustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternate_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('geo_location', models.CharField(blank=True, max_length=255, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_detail', to='physical_medicals.physicalmedicalcase')),
            ],
        ),
    ]
