# Generated by Django 5.2.7 on 2026-01-29 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_remove_clientspoc_receive_email_for_and_more'),
        ('client_branch', '0001_initial'),
        ('master_management', '0009_alter_doctorspecialization_image'),
        ('physical_medical_master', '0004_caseformaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalMedicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('case_received_datetime', models.DateTimeField(blank=True, null=True)),
                ('case_received_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.casereceivedmode')),
                ('case_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.casestatus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'physical_medicals_physicalmedicalcase',
            },
        ),
        migrations.CreateModel(
            name='PhysicalMedicalCaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('application_no', models.CharField(max_length=50)),
                ('customer_pay_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preferred_appointment_datetime', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_detail', to='physical_medicals.physicalmedicalcase')),
                ('case_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.casefor')),
                ('case_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.casetype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.customerprofile')),
                ('dhoc_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.dhocpaymentoption')),
                ('generic_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.mastergenerictest')),
                ('medical_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.medicaltest')),
                ('payment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.paymenttype')),
                ('preferred_visit_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.preferredvisittype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'physical_medicals_physicalmedicalcasedetail',
            },
        ),
        migrations.CreateModel(
            name='PhysicalMedicalClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('received_by_name', models.CharField(blank=True, max_length=255)),
                ('received_mobile', models.CharField(blank=True, max_length=15)),
                ('received_email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_detail', to='physical_medicals.physicalmedicalcase')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('client_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_branch.clientbranch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.customertype')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.masterproduct')),
                ('service_offered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.serviceoffered')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'physical_medicals_physicalmedicalclientdetail',
            },
        ),
        migrations.CreateModel(
            name='PhysicalMedicalCustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternate_number', models.CharField(blank=True, max_length=15)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True)),
                ('area_locality', models.CharField(blank=True, max_length=255)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('geo_location', models.CharField(blank=True, max_length=255)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_detail', to='physical_medicals.physicalmedicalcase')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.gender')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.state')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'physical_medicals_physicalmedicalcustomerdetail',
            },
        ),
        migrations.CreateModel(
            name='PhysicalMedicalDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dependent_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='physical_medicals.physicalmedicalcase')),
                ('case_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.casefor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.gender')),
                ('medical_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='physical_medical_master.medicaltest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'physical_medicals_physicalmedicaldependent',
            },
        ),
    ]
