# Generated by Django 5.2.7 on 2026-01-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_medicals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalmedicalcase',
            name='assigned_executive',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
