# Generated by Django 5.2.7 on 2026-01-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_medicals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicalmedicalcasedetail',
            name='dhoc_advance_payment',
        ),
        migrations.RemoveField(
            model_name='physicalmedicalcasedetail',
            name='welleazy_generic_test',
        ),
        migrations.AddField(
            model_name='physicalmedicalcasedetail',
            name='arrange_appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='physicalmedicalcasedetail',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='physicalmedicalcasedetail',
            name='dhoc_payment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='physicalmedicalcasedetail',
            name='generic_test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='physicalmedicalcasedetail',
            name='case_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='physicalmedicalcasedetail',
            name='customer_pay_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='physicalmedicalcasedetail',
            name='medical_test',
            field=models.CharField(max_length=100),
        ),
    ]
