# Generated by Django 5.2.7 on 2026-01-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_medicals', '0002_remove_physicalmedicalcasedetail_dhoc_advance_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalmedicalcustomerdetail',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
