# Generated by Django 5.2.7 on 2026-01-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_medicals', '0003_alter_physicalmedicalcustomerdetail_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalmedicalcasedetail',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
