# Generated by Django 6.0.1 on 2026-01-30 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_masters', '0002_emailnotificationtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('corporate_code', models.CharField(blank=True, max_length=100, null=True)),
                ('corporate_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('landline_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('head_office_address', models.TextField(blank=True, null=True)),
                ('branch_office_address', models.TextField(blank=True, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('broker', models.CharField(blank=True, max_length=255, null=True)),
                ('ops_spoc', models.CharField(blank=True, max_length=255, null=True)),
                ('service_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True)),
                ('home_visit_charges', models.CharField(blank=True, max_length=255, null=True)),
                ('account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_partner_id', models.CharField(blank=True, max_length=100, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('billing_email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_sponsored', models.CharField(blank=True, max_length=255, null=True)),
                ('total_non_sponsored', models.CharField(blank=True, max_length=255, null=True)),
                ('is_dependent_sponsored', models.BooleanField(default=False)),
                ('case_registration_mail_auto_triggered', models.BooleanField(default=False)),
                ('separate_access', models.BooleanField(default=False)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='client_backgrounds/')),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_masters.businesstype')),
                ('client_agreement_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_masters.clientagreementfrom')),
                ('corporate_partnership_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_masters.partnershipstatus')),
                ('corporate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_masters.corporatetype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('frequency_of_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_masters.paymentfrequency')),
                ('members_sponsored', models.ManyToManyField(blank=True, to='client_masters.memberrelationtype')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_masters.source')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('visit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_masters.visittype')),
                ('welleazy_crm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_masters.welleazycrm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='client_documents/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='client.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientSPOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('person_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=20)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spocs', to='client.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_masters.designation')),
                ('receive_email_for', models.ManyToManyField(blank=True, to='client_masters.emailnotificationtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
