# Generated by Django 6.0.1 on 2026-01-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('client_masters', '0002_emailnotificationtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientspoc',
            name='receive_email_for',
        ),
        migrations.AddField(
            model_name='clientspoc',
            name='receive_email_for',
            field=models.ManyToManyField(blank=True, to='client_masters.emailnotificationtype'),
        ),
    ]
