# Generated by Django 6.0.1 on 2026-02-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_login_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='corporate_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
