# Generated by Django 6.0.1 on 2026-01-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_clientspoc_receive_email_for_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='branch_office_addresses',
            new_name='branch_office_address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='separate_account',
            new_name='separate_access',
        ),
    ]
