# Generated by Django 6.0.1 on 2026-02-04 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_corporate_code'),
        ('master_management', '0003_casestatus'),
        ('other_services', '0002_eyedentaltreatment'),
        ('service_provider', '0002_serviceprovider_corporate_companies_and_more'),
        ('sub_client', '0001_initial'),
        ('test_individual', '0002_alter_individualtest_status'),
        ('test_package', '0004_alter_testpackage_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('camp_request_from', models.CharField(choices=[('Main Client', 'Main Client'), ('Sub Client', 'Sub Client')], max_length=15)),
                ('camp_datetime', models.DateTimeField()),
                ('camp_location', models.CharField(max_length=255)),
                ('camp_address', models.TextField()),
                ('expected_medical_count', models.PositiveIntegerField(default=0)),
                ('completed_medical_count', models.PositiveIntegerField(default=0)),
                ('case_status', models.CharField(choices=[('Fresh Case', 'Fresh Case'), ('Future Date', 'Future Date'), ('On Going', 'On Going'), ('Partially Done', 'Partially Done'), ('Completed', 'Completed')], default='FRESH', max_length=20)),
                ('client_spoc_name', models.CharField(blank=True, max_length=255)),
                ('client_spoc_mobile', models.CharField(blank=True, max_length=20)),
                ('client_spoc_email', models.EmailField(blank=True, max_length=254)),
                ('network_spoc_name', models.CharField(blank=True, max_length=255)),
                ('network_spoc_mobile', models.CharField(blank=True, max_length=20)),
                ('network_spoc_email', models.EmailField(blank=True, max_length=254)),
                ('client_invoice_belong_to', models.CharField(choices=[('WELLEAZY_LAB', 'Welleazy Lab'), ('WELLEAZY_HEALTHTECH', 'Welleazyhealthtech')], max_length=30)),
                ('client_cost_per_case', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_client_billable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('network_cost_per_case', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('network_payable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('medical_hard_copy_required', models.BooleanField(default=False)),
                ('special_requirement', models.TextField(blank=True)),
                ('camp_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.city')),
                ('camp_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.state')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('main_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_camps', to='client.client')),
                ('network_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service_provider.serviceprovider')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_package.testpackage')),
                ('sub_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sub_client.subclient')),
                ('tests', models.ManyToManyField(blank=True, to='test_individual.individualtest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
