# Generated by Django 6.0.1 on 2026-02-05 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_services', '0003_medicalcamp'),
        ('test_individual', '0002_alter_individualtest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcamp',
            name='tests',
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='tests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_individual.individualtest'),
        ),
    ]
