# Generated by Django 6.0.1 on 2026-02-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_services', '0004_remove_medicalcamp_tests_medicalcamp_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcamp',
            name='case_status',
        ),
        migrations.AddField(
            model_name='medicalcamp',
            name='camp_status',
            field=models.CharField(choices=[('Fresh Case', 'Fresh Case'), ('Future Date', 'Future Date'), ('On Going', 'On Going'), ('Partially Done', 'Partially Done'), ('Completed', 'Completed')], default='FRESH', max_length=20),
        ),
    ]
