# Generated by Django 6.0.1 on 2026-02-05 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0003_casestatus'),
        ('other_services', '0005_remove_medicalcamp_case_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalcamp',
            old_name='case_id',
            new_name='camp_id',
        ),
        migrations.CreateModel(
            name='CampCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='case_documents/')),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='other_services.medicalcamp')),
                ('case_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.casestatus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer_gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.mastergender')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
