# Generated by Django 6.0.1 on 2026-02-06 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0003_casestatus'),
        ('other_services', '0006_rename_case_id_medicalcamp_camp_id_campcase'),
        ('test_package', '0004_alter_testpackage_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('NA', 'NA'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly'), ('Annually', 'Annually')], default='NA', max_length=20)),
                ('frequency', models.CharField(choices=[('NA', 'NA'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly'), ('Annually', 'Annually')], default='NA', max_length=20)),
                ('limitation', models.CharField(blank=True, max_length=255)),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('corporate_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_package.testpackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.masterproduct')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.masterproductsubcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
