# Generated by Django 6.0.1 on 2026-02-06 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_corporate_code'),
        ('doctor', '0002_doctoravailability_created_at_and_more'),
        ('other_services', '0007_chp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfOHC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OHC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('corporate_requirements', models.TextField(blank=True)),
                ('crm_name', models.CharField(blank=True, max_length=255)),
                ('corporate_address', models.TextField(blank=True)),
                ('spoc_name', models.CharField(blank=True, max_length=255)),
                ('spoc_email', models.EmailField(blank=True, max_length=254)),
                ('spoc_mobile', models.CharField(blank=True, max_length=20)),
                ('service_start_date', models.DateTimeField(blank=True, null=True)),
                ('agreement_date', models.DateTimeField(blank=True, null=True)),
                ('relationship_end_date', models.DateTimeField(blank=True, null=True)),
                ('agreement_upload', models.FileField(blank=True, null=True, upload_to='ohc_agreements/')),
                ('client_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('service_provider_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('doctor_qualifications', models.CharField(blank=True, max_length=255)),
                ('doctor_certificate_link', models.URLField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor.doctor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('type_of_ohc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='other_services.typeofohc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
