# Generated by Django 6.0.1 on 2026-02-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_corporate_code'),
        ('client_branch', '0001_initial'),
        ('client_customer', '0008_alter_clientcustomer_employee_code_and_more'),
        ('master_management', '0003_casestatus'),
        ('other_services', '0008_typeofohc_ohc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeTreatmentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_branch.clientbranch')),
                ('case_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.masterrelationship')),
                ('case_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.casestatus')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.city')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eye_treatment_cases', to='client_customer.clientcustomer')),
                ('eye_treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='other_services.eyedentaltreatment')),
                ('relationship_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eye_treatment_cases', to='client_customer.clientcustomerdependent')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.state')),
            ],
        ),
    ]
