# Generated by Django 6.0.1 on 2026-02-07 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_corporate_code'),
        ('client_branch', '0001_initial'),
        ('client_customer', '0008_alter_clientcustomer_employee_code_and_more'),
        ('master_management', '0003_casestatus'),
        ('other_services', '0010_eyetreatmentcase_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalTreatmentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client_branch.clientbranch')),
                ('case_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.masterrelationship')),
                ('case_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.casestatus')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.city')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dental_treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='other_services.eyedentaltreatment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dental_treatment_cases', to='client_customer.clientcustomer')),
                ('relationship_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dental_treatment_cases', to='client_customer.clientcustomerdependent')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.state')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
