# Generated by Django 5.2.7 on 2026-01-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_opinion_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReceivedMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
