# Generated by Django 6.0.1 on 2026-02-04 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_alter_client_corporate_code'),
        ('client_branch', '0001_initial'),
        ('doctor', '0002_doctoravailability_created_at_and_more'),
        ('master_management', '0003_casestatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_rec_mode', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('WhatsApp', 'WhatsApp'), ('Walk-in', 'Walk-in'), ('Website', 'Website')], default='Email', max_length=50)),
                ('case_rec_date_time', models.DateTimeField(blank=True, null=True)),
                ('customer_type', models.CharField(choices=[('New', 'New'), ('Existing', 'Existing')], default='New', max_length=50)),
                ('members_sponsored', models.CharField(blank=True, max_length=255, null=True)),
                ('received_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_partner_id', models.CharField(blank=True, max_length=100, null=True)),
                ('case_for', models.CharField(choices=[('Self', 'Self'), ('Dependent', 'Dependent')], default='Self', max_length=50)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(max_length=20)),
                ('alternate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('no_of_free_consultations', models.PositiveIntegerField(default=0)),
                ('no_of_consultations_used', models.PositiveIntegerField(default=0)),
                ('upload_document', models.FileField(blank=True, null=True, upload_to='consultation/documents/')),
                ('application_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_profile', models.CharField(choices=[('Normal', 'Normal'), ('HNI', 'HNI')], default='Normal', max_length=50)),
                ('payment_type', models.CharField(choices=[('Corporate Paid', 'Corporate Paid'), ('Customer Paid', 'Customer Paid')], default='Corporate Paid', max_length=50)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=250.0, max_digits=10)),
                ('payment_mode', models.CharField(blank=True, choices=[('Online', 'Online'), ('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], max_length=50, null=True)),
                ('paying_to', models.CharField(blank=True, choices=[('Welleazy', 'Welleazy'), ('Provider', 'Provider')], max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Partially Paid', 'Partially Paid')], default='Pending', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_received_date_time', models.DateTimeField(blank=True, null=True)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('appointment_date_time', models.DateTimeField(blank=True, null=True)),
                ('appointment_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled')], default='Scheduled', max_length=50)),
                ('follow_up_date_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assigned_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultation_cases', to=settings.AUTH_USER_MODEL)),
                ('branch_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_cases', to='client_branch.clientbranch')),
                ('case_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_cases', to='master_management.casestatus')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.city')),
                ('consultation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_cases', to='master_management.masterproduct')),
                ('corporate_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_cases', to='client.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('doctor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_cases', to='doctor.doctor')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.mastergender')),
                ('preferred_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.doctorlanguage')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_cases', to='master_management.masterproductsubcategory')),
                ('specialities_test_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_cases', to='master_management.masterspecialtiestest')),
                ('sponsor_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.masterrelationship')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.state')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('welleazy_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_cases', to='master_management.masterbranch')),
            ],
            options={
                'db_table': 'consultation_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
