# Generated by Django 6.0.1 on 2026-02-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_remove_consultationcase_appointment_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationcase',
            name='assigned_executive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
