# Generated by Django 6.0.1 on 2026-02-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_consultationcase_assigned_executive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationcase',
            name='case_for',
            field=models.CharField(choices=[('Self', 'Self'), ('Dependent', 'Dependent'), ('Both', 'Both')], default='Self', max_length=50),
        ),
        migrations.AlterField(
            model_name='consultationcase',
            name='case_rec_mode',
            field=models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Call', 'Call'), ('Client Online Updations', 'Client Online Updations'), ('Client Sales Person Updations', 'Client Sales Person Updations'), ('Customer Online Updations', 'Customer Online Updations')], default='Email', max_length=50),
        ),
        migrations.AlterField(
            model_name='consultationcase',
            name='customer_profile',
            field=models.CharField(choices=[('Normal', 'Normal'), ('HNI', 'HNI'), ('NRI', 'NRI')], default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='consultationcase',
            name='customer_type',
            field=models.CharField(choices=[('New', 'New'), ('Registered', 'Registered')], default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='consultationcase',
            name='paying_to',
            field=models.CharField(blank=True, choices=[('Welleazy', 'Welleazy'), ('DC/Hospital', 'DC/Hospital')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultationcase',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Cash', 'Cash'), ('UPI', 'UPI')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consultationcase',
            name='payment_status',
            field=models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
