# Generated by Django 6.0.1 on 2026-02-13 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_alter_consultationcase_gender'),
        ('master_management', '0005_delete_mastergender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationappointment',
            options={},
        ),
        migrations.AlterModelTable(
            name='consultationappointment',
            table=None,
        ),
        migrations.CreateModel(
            name='ConsultationCaseDependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('person_name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_mode', models.CharField(blank=True, choices=[('Online', 'Online'), ('Cash', 'Cash'), ('UPI', 'UPI')], max_length=50, null=True)),
                ('paying_to', models.CharField(blank=True, choices=[('Welleazy', 'Welleazy'), ('DC/Hospital', 'DC/Hospital')], max_length=50, null=True)),
                ('payment_status', models.CharField(choices=[('Received', 'Received'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_received_date_time', models.DateTimeField(blank=True, null=True)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('case_type', models.CharField(blank=True, max_length=50, null=True)),
                ('follow_up_date_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='consultation.consultationcase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('preferred_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.masterlanguage')),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.masterrelationship')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultation_case_dependents',
                'ordering': ['created_at'],
            },
        ),
    ]
