# Generated by Django 6.0.1 on 2026-02-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_alter_consultationappointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationcase',
            name='sponsor_status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Partial', 'Partial')], max_length=100, null=True),
        ),
    ]
