# Generated by Django 6.0.1 on 2026-02-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_alter_consultationcasedependent_case_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationcase',
            name='upload_document',
        ),
    ]
