# Generated by Django 6.0.1 on 2026-02-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0009_remove_consultationcase_upload_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationcase',
            name='case_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
