# Generated by Django 6.0.1 on 2026-02-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0010_consultationcase_case_id'),
    ]

    operations = [
    ]
