# Generated by Django 6.0.1 on 2026-02-16 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0012_consultationdoctordetails_and_more'),
        ('master_management', '0005_delete_mastergender'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationdoctordetails',
            name='case_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.casestatus'),
        ),
        migrations.AddField(
            model_name='consultationdoctordetails',
            name='preferred_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.masterlanguage'),
        ),
    ]
