# Generated by Django 6.0.1 on 2026-01-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE_EMPLOYEE', 'Corporate Employee'), ('DEPENDANT', 'Dependant'), ('HNI_VIP', 'HNI/VIP')], default='INDIVIDUAL', max_length=30)),
                ('corporate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SCHEDULED', 'Scheduled')], default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('MOBILE_APP', 'Mobile App'), ('CRM_MANUAL', 'CRM Manual Entry'), ('CALL_CENTER', 'Call Center'), ('EMAIL', 'Email'), ('WALK_IN', 'Walk-in'), ('HR_PORTAL', 'HR Portal')], default='CRM_MANUAL', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
