# Generated by Django 6.0.1 on 2026-01-12 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='case',
            old_name='corporate_name',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='case',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='customer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='diagnostic_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='case',
            name='employee_to_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='case',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='case',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='followup_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='home_visit_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='case',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='payment_type',
            field=models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid'), ('corporate', 'Corporate Billing'), ('insurance', 'Insurance'), ('cod', 'Cash on Delivery')], default='PREPAID', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='received_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='received_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='received_by_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='service_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='case',
            name='service_type',
            field=models.CharField(choices=[('diagnostic_test', 'Diagnostic Test'), ('doctor_consultation', 'Doctor Consultation'), ('pharmacy', 'Pharmacy Order'), ('health_package', 'Health Package'), ('sponsored', 'Sponsored Package'), ('eye_care', 'Eye Care'), ('dental', 'Dental Care'), ('gym', 'Gym/Fitness')], default='exit', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='case',
            name='vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='visit_type',
            field=models.CharField(choices=[('home', 'Home Visit'), ('center', 'At Center'), ('video', 'Video Consultation'), ('hybrid', 'Hybrid')], default='HOME_COLLECTION', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('corporate_employee', 'Corporate Employee'), ('dependant', 'Dependant'), ('hni_vip', 'HNI/VIP')], max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='phone_number',
            field=models.CharField(default='HOME', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('mobile_app', 'Mobile App'), ('crm_manual', 'CRM Manual Entry'), ('call_center', 'Call Center'), ('email', 'Email'), ('walk_in', 'Walk-in'), ('hr_portal', 'HR Portal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('scheduled', 'Scheduled')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.corporate'),
        ),
    ]
