# Generated by Django 6.0.1 on 2026-01-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_corporate_rename_corporate_name_case_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='corporate',
        ),
        migrations.RemoveField(
            model_name='case',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='case',
            name='email',
        ),
        migrations.RemoveField(
            model_name='case',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='case',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='case',
            name='payment_type',
            field=models.CharField(choices=[('PREPAID', 'Prepaid'), ('POSTPAID', 'Postpaid'), ('CORPORATE', 'Corporate Billing'), ('INSURANCE', 'Insurance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='service_type',
            field=models.CharField(choices=[('HOME_COLLECTION', 'Home Collection'), ('LAB_VISIT', 'Lab Visit'), ('DOCTOR_VISIT', 'Doctor Visit')], max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='source',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('MOBILE_APP', 'Mobile App'), ('CRM_MANUAL', 'CRM Manual Entry'), ('CALL_CENTER', 'Call Center'), ('EMAIL', 'Email'), ('WALK_IN', 'Walk-in'), ('HR_PORTAL', 'HR Portal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SCHEDULED', 'Scheduled')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='visit_type',
            field=models.CharField(choices=[('HOME', 'Home'), ('CENTER', 'Center')], max_length=30),
        ),
    ]
