# Generated by Django 6.0.1 on 2026-01-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_deleted_at_case_updated_at_case_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='deleted_at',
        ),
    ]
