# Generated by Django 6.0.1 on 2026-01-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_remove_case_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='customer_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE_EMPLOYEE', 'Corporate Employee'), ('DEPENDANT', 'Dependant'), ('HNI_VIP', 'HNI/VIP')], default='INDIVIDUAL', max_length=30),
        ),
        migrations.AddField(
            model_name='case',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Corporate',
        ),
    ]
