# Generated by Django 6.0.1 on 2026-01-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_case_patient_email_case_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='corporate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
