# Generated by Django 6.0.1 on 2026-01-13 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_case_corporate_case_employee_id'),
        ('corporates', '0001_initial'),
        ('diagnostic_center', '0005_alter_diagnosticaccreditation_iso_type'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='customer_notes',
        ),
        migrations.RemoveField(
            model_name='case',
            name='department',
        ),
        migrations.RemoveField(
            model_name='case',
            name='diagnostic_center',
        ),
        migrations.RemoveField(
            model_name='case',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='case',
            name='employee_to_pay',
        ),
        migrations.RemoveField(
            model_name='case',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='case',
            name='followup_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='followup_remark',
        ),
        migrations.RemoveField(
            model_name='case',
            name='home_visit_charge',
        ),
        migrations.RemoveField(
            model_name='case',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='case',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='case',
            name='received_by_email',
        ),
        migrations.RemoveField(
            model_name='case',
            name='received_by_name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='received_by_phone',
        ),
        migrations.RemoveField(
            model_name='case',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='scheduled_time',
        ),
        migrations.RemoveField(
            model_name='case',
            name='service_address',
        ),
        migrations.RemoveField(
            model_name='case',
            name='service_charge',
        ),
        migrations.RemoveField(
            model_name='case',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='case',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='case',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='case',
            name='visit_type',
        ),
        migrations.AlterField(
            model_name='case',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corporates.corporate'),
        ),
        migrations.AlterField(
            model_name='case',
            name='customer_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('CORPORATE', 'Corporate Employee'), ('DEPENDANT', 'Dependant'), ('VIP', 'HNI/VIP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='patient_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='patient_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='case',
            name='source',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('MOBILE', 'Mobile App'), ('CRM', 'CRM Manual Entry'), ('CALL', 'Call Center'), ('EMAIL', 'Email'), ('WALKIN', 'Walk-in'), ('HR', 'HR Portal')], max_length=20),
        ),
        migrations.CreateModel(
            name='CaseAdditionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('received_by_name', models.CharField(max_length=255)),
                ('received_by_phone', models.CharField(max_length=20)),
                ('received_by_email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('followup_date', models.DateField(null=True)),
                ('followup_remark', models.TextField(null=True)),
                ('notes', models.TextField()),
                ('internal_notes', models.TextField()),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseFinancialDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('PREPAID', 'Prepaid'), ('POSTPAID', 'Postpaid'), ('CORPORATE', 'Corporate Billing'), ('INSURANCE', 'Insurance'), ('COD', 'Cash on Delivery')], max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('home_visit_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('service_type', models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic Test'), ('DOCTOR', 'Doctor Consultation'), ('PHARMACY', 'Pharmacy Order'), ('PACKAGE', 'Health Package'), ('SPONSORED', 'Sponsored Package'), ('EYE', 'Eye Care'), ('DENTAL', 'Dental Care'), ('GYM', 'Gym/Fitness')], max_length=30)),
                ('visit_type', models.CharField(choices=[('HOME', 'Home'), ('CENTER', 'At Center')], max_length=20)),
                ('scheduled_date', models.DateField(null=True)),
                ('scheduled_time', models.TimeField(null=True)),
                ('address', models.TextField(null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('diagnostic_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_services', to='diagnostic_center.diagnosticcenter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
