# Generated by Django 6.0.1 on 2026-01-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_remove_case_customer_notes_remove_case_department_and_more'),
        ('diagnostic_center', '0005_alter_diagnosticaccreditation_iso_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseservicedetails',
            name='diagnostic_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnostic_center.diagnosticcenter'),
        ),
    ]
