# Generated by Django 6.0.1 on 2026-01-14 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_caseservicedetails_diagnostic_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefinancialdetails',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='cases.case'),
        ),
    ]
