# Generated by Django 6.0.1 on 2026-02-02 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_client_login_type'),
        ('client_customer', '0002_clientcustomer_geo_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondOpinionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('case_type', models.CharField(choices=[('Interpretation', 'Interpretation'), ('Medical Review', 'Medical Review'), ('Tele-Consultation', 'Tele-Consultation')], max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('application_number', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=100)),
                ('case_received_mode', models.CharField(blank=True, choices=[('Email', 'Email'), ('WhatsApp', 'WhatsApp'), ('Portal', 'Portal'), ('Direct', 'Direct')], max_length=50, null=True)),
                ('interpretation_type', models.CharField(blank=True, choices=[('ECG', 'ECG'), ('MRI', 'MRI'), ('CT Scan', 'CT Scan'), ('X-Ray', 'X-Ray'), ('Lab Report', 'Lab Report'), ('TMT', 'TMT')], max_length=50, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='second_opinion/reports/')),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client')),
                ('client_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_customer.clientcustomer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
