# Generated by Django 5.2.7 on 2026-01-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondOpinionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('application_number', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=100)),
                ('remark', models.TextField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='second_opinion/reports/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
