# Generated by Django 6.0.1 on 2026-02-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_opinion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondopinioncase',
            name='interpretation_type',
            field=models.CharField(blank=True, choices=[('ECG', 'ECG'), ('TMT', 'TMT')], max_length=50, null=True),
        ),
    ]
