# Generated by Django 6.0.1 on 2026-02-02 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0001_initial'),
        ('second_opinion', '0002_alter_secondopinioncase_interpretation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondopinioncase',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.city'),
        ),
        migrations.AddField(
            model_name='secondopinioncase',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.mastergender'),
        ),
        migrations.AddField(
            model_name='secondopinioncase',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.masterinsurancecompany'),
        ),
        migrations.AddField(
            model_name='secondopinioncase',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.masterrelationship'),
        ),
        migrations.AddField(
            model_name='secondopinioncase',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.state'),
        ),
    ]
