# Generated by Django 6.0.1 on 2026-02-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_opinion', '0003_secondopinioncase_city_secondopinioncase_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondopinioncase',
            name='case_received_mode',
            field=models.CharField(blank=True, choices=[('Insurer', 'Insurer'), ('Email', 'Email'), ('SMS', 'SMS'), ('FTP', 'FTP')], max_length=50, null=True),
        ),
    ]
