# Generated by Django 6.0.1 on 2026-02-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_opinion', '0004_alter_secondopinioncase_case_received_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondopinioncase',
            name='case_type',
            field=models.CharField(choices=[('Interpretation', 'Interpretation'), ('Medication', 'Medication'), ('Policy Number', 'Policy Number')], max_length=50),
        ),
    ]
