# Generated by Django 6.0.1 on 2026-02-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_opinion', '0005_alter_secondopinioncase_case_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondopinioncase',
            name='case_type',
            field=models.CharField(choices=[('Interpretation', 'Interpretation'), ('Digitization', 'Digitization')], max_length=50),
        ),
    ]
