# Generated by Django 6.0.1 on 2026-02-03 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('second_opinion', '0006_alter_secondopinioncase_case_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secondopinioncase',
            name='case_status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned'), ('In Process', 'In Process'), ('Incomplete Report', 'Incomplete Report'), ('Completed', 'Completed'), ('Doctor TAT', 'Doctor TAT')], default='Unassigned', max_length=50),
        ),
        migrations.AddField(
            model_name='secondopinioncase',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor'),
        ),
        migrations.AddField(
            model_name='secondopinioncase',
            name='qc_executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_opinion_qc_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
