# Generated by Django 6.0.1 on 2026-01-28 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_remove_clientspoc_receive_email_for_and_more'),
        ('master_management', '0009_alter_doctorspecialization_image'),
        ('test_management_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default='Active', max_length=10)),
                ('product_sku', models.CharField(editable=False, max_length=50, unique=True)),
                ('test_name', models.CharField(max_length=255)),
                ('test_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('retail_test_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('corporate_test_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hni_test_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('discount_test_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('common_test_name', models.CharField(blank=True, max_length=255)),
                ('remark', models.TextField(blank=True)),
                ('test_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tests/images/')),
                ('complimentary_tba', models.CharField(choices=[('Complimentary', 'Complimentary'), ('TBA', 'TBA')], default='TBA', max_length=15)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.city')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('health_concern_type', models.ManyToManyField(blank=True, to='test_management_master.healthconcerntype')),
                ('test_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_management_master.testtype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('visit_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.mastervisittype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
