# Generated by Django 6.0.1 on 2026-01-30 06:28

import apps.doctor.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_master', '0002_doctortype_created_at_doctortype_created_by_and_more'),
        ('master_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_id', models.CharField(default=apps.doctor.models.generate_doctor_id, editable=False, max_length=20, unique=True)),
                ('doctor_name', models.CharField(max_length=150)),
                ('mobile_no', models.CharField(max_length=15)),
                ('alternate_contact', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('registration_no', models.CharField(max_length=100)),
                ('pan_card', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('experience_years', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_document_pending', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('doctor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor_master.doctortype')),
                ('empanel_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor_master.empanelfor')),
                ('languages', models.ManyToManyField(to='master_management.doctorlanguage')),
                ('meet_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor_master.meetlocation')),
                ('qualifications', models.ManyToManyField(to='master_management.doctorqualification')),
                ('specializations', models.ManyToManyField(to='master_management.doctorspecialization')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_management.state')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('night', 'Night')], max_length=10)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('copy_time_from_montosun', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='doctor_documents/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='doctor.doctor')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor_master.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(default=apps.doctor.models.generate_service_id, editable=False, max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='doctor.doctor')),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_master.empanelfor')),
            ],
        ),
    ]
