# Generated by Django 6.0.1 on 2026-01-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_client', '0002_subclient_login_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subclient',
            name='corporate_type',
        ),
        migrations.RemoveField(
            model_name='subclient',
            name='login_type',
        ),
    ]
