# Generated by Django 6.0.1 on 2026-01-29 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_masters', '0002_emailnotificationtype'),
        ('sub_client', '0003_remove_subclient_corporate_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclient',
            name='corporate_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_masters.corporatetype'),
        ),
    ]
