# Generated by Django 6.0.1 on 2026-01-30 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('master_management', '0001_initial'),
        ('test_individual', '0001_initial'),
        ('test_management_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product_sku', models.CharField(editable=False, max_length=50, unique=True)),
                ('package_name', models.CharField(max_length=255)),
                ('retail_package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('corporate_package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hni_package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('discount_package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default='Active', max_length=10)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('package_validity_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('package_headline_details', models.CharField(blank=True, max_length=255)),
                ('package_details', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/images/')),
                ('mer_form', models.FileField(blank=True, null=True, upload_to='packages/mer/')),
                ('fitness_form', models.FileField(blank=True, null=True, upload_to='packages/fitness/')),
                ('complimentary_tba', models.CharField(choices=[('Complimentary', 'Complimentary'), ('TBA', 'TBA')], default='TBA', max_length=15)),
                ('checkup_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_management_master.checkuptype')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.city')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='client.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.mastergender')),
                ('plan_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_management_master.plancategory')),
                ('tests_included', models.ManyToManyField(blank=True, to='test_individual.individualtest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('visit_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.mastervisittype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
