# Generated by Django 6.0.1 on 2026-01-28 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_package', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testpackage',
            old_name='validity_date',
            new_name='package_validity_date',
        ),
    ]
