# Generated by Django 6.0.1 on 2026-01-28 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0010_merge_20260128_1721'),
        ('test_package', '0002_rename_validity_date_testpackage_package_validity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpackage',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.mastergender'),
        ),
    ]
