# Generated by Django 6.0.1 on 2026-01-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpackage',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
