# Generated by Django 6.0.1 on 2026-02-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_package', '0004_alter_testpackage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpackage',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
