# Generated by Django 6.0.1 on 2026-02-02 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_management', '0002_gymvendors'),
        ('test_management_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GymPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('gym_sku', models.CharField(editable=False, max_length=20, unique=True)),
                ('package_name', models.CharField(max_length=150)),
                ('quantity', models.PositiveIntegerField()),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
                ('discounted_package_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('package_validity_date', models.DateField()),
                ('package_headline_details', models.CharField(blank=True, max_length=255)),
                ('package_description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gym_packages/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_management.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('plan_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_management_master.plancategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_management.gymvendors')),
                ('package_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gympackage.packagepricetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
