# Generated by Django 6.0 on 2026-01-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemapping',
            name='sub_product',
        ),
        migrations.AddField(
            model_name='servicemapping',
            name='sub_products',
            field=models.ManyToManyField(related_name='service_mappings', to='master_management.masterproductsubcategory'),
        ),
    ]
