# Generated by Django 6.0 on 2026-01-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0002_remove_servicemapping_sub_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterbranch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='masterbranch',
            name='state',
        ),
        migrations.AddField(
            model_name='masterbranch',
            name='states',
            field=models.ManyToManyField(related_name='branches', to='master_management.state'),
        ),
    ]
