# Generated by Django 6.0.1 on 2026-02-04 11:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_remove_consultationcase_appointment_date_time_and_more'),
        ('doctor', '0002_doctoravailability_created_at_and_more'),
        ('master_management', '0003_casestatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorLanguage',
            new_name='MasterLanguage',
        ),
    ]
