# Generated by Django 6.0.1 on 2026-02-12 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_customer', '0009_alter_clientcustomer_gender_and_more'),
        ('consultation', '0005_alter_consultationcase_gender'),
        ('lead_management', '0007_alter_individualclient_gender_and_more'),
        ('master_management', '0004_rename_doctorlanguage_masterlanguage'),
        ('other_services', '0012_alter_campcase_customer_gender'),
        ('second_opinion', '0008_alter_secondopinioncase_gender'),
        ('test_package', '0005_alter_testpackage_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterGender',
        ),
    ]
