# Generated by Django 5.2.7 on 2026-01-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0005_mastervisittype_alter_mastergenerictest_visit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspecialization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/doctor_specializations/'),
        ),
    ]
