# Generated by Django 6.0.1 on 2026-01-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0006_alter_doctorspecialization_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masteruploadformat',
            name='upload_format',
            field=models.FileField(upload_to='media/upload_formats/'),
        ),
    ]
