# Generated by Django 5.2.7 on 2026-01-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0006_alter_doctorspecialization_image'),
        ('master_management', '0006_alter_doctorspecialization_image_and_more'),
    ]

    operations = [
    ]
