# Generated by Django 5.2.7 on 2026-01-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0007_alter_masteruploadformat_upload_format'),
        ('master_management', '0007_merge_20260123_1823'),
    ]

    operations = [
    ]
