# Generated by Django 6.0.1 on 2026-01-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0007_alter_masteruploadformat_upload_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspecialization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_specializations/'),
        ),
    ]
