# Generated by Django 6.0.1 on 2026-01-28 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0006_alter_doctorspecialization_image'),
        ('master_management', '0007_alter_masteruploadformat_upload_format'),
    ]

    operations = [
    ]
