# Generated by Django 5.2.7 on 2026-01-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0008_merge_20260127_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspecialization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_specializations/'),
        ),
    ]
