# Generated by Django 5.2.7 on 2026-01-27 09:57
# Generated by Django 6.0.1 on 2026-01-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('master_management', '0008_merge_20260127_1527'),
=======
        ('master_management', '0008_merge_20260128_1027'),
>>>>>>> c8e83f2dbf1bf2697c3e1b68ae379e9e5d2525fb
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspecialization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_specializations/'),
        ),
    ]
