# Generated by Django 6.0.1 on 2026-01-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0008_merge_20260128_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspecialization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_specializations/'),
        ),
    ]
