# Generated by Django 6.0.1 on 2026-01-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0009_alter_doctorspecialization_image'),
        ('master_management', '0009_mastergender_masterrelationship'),
    ]

    operations = [
    ]
