# Generated by Django 6.0.1 on 2026-02-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_corporate_code'),
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='corporate_companies',
            field=models.ManyToManyField(blank=True, related_name='corporate_providers', to='client.client'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='client_company',
            field=models.ManyToManyField(blank=True, related_name='service_providers', to='client.client'),
        ),
    ]
