# Generated by Django 6.0.1 on 2026-01-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spoc',
            old_name='person_name',
            new_name='name',
        ),
    ]
