# Generated by Django 6.0.1 on 2026-01-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0002_rename_person_name_spoc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providervoucher',
            name='Remarks',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
