# Generated by Django 6.0.1 on 2026-01-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0003_alter_providervoucher_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providervoucher',
            name='voucher_type',
        ),
    ]
