# Generated by Django 6.0.1 on 2026-01-27 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0005_providerregistrationlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerregistrationlink',
            name='provider',
            field=models.ForeignKey(default=36, on_delete=django.db.models.deletion.CASCADE, to='service_provider.serviceprovider'),
            preserve_default=False,
        ),
    ]
