# Generated by Django 6.0.1 on 2026-01-27 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0006_providerregistrationlink_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerregistrationlink',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service_provider.serviceprovider'),
        ),
    ]
