# Generated by Django 6.0.1 on 2026-01-27 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_management', '0006_alter_doctorspecialization_image'),
        ('service_provider', '0007_alter_providerregistrationlink_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerregistrationlink',
            name='provider_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_management.mastertypeofprovider'),
        ),
    ]
