# Generated by Django 6.0.1 on 2026-01-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_clientspoc_receive_email_for_and_more'),
        ('service_provider', '0008_alter_providerregistrationlink_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='client_company',
            field=models.ManyToManyField(blank=True, to='client.client'),
        ),
    ]
