# Generated by Django 6.0.1 on 2026-01-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_management_master', '0002_checkuptype_gender_plancategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='updated_by',
        ),
    ]
