# Generated by Django 6.0.1 on 2026-01-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_management_master', '0003_remove_gender_created_by_remove_gender_updated_by'),
        ('test_package', '0003_alter_testpackage_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
