# Generated by Django 6.0.1 on 2026-01-24 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('client_branch', '0001_initial'),
        ('master_management', '0007_alter_masteruploadformat_upload_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('member_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('packages', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('area_locality', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('members_sponsored', models.CharField(blank=True, max_length=255, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True)),
                ('two_fa_enabled', models.BooleanField(default=False)),
                ('account_activation_url', models.URLField(blank=True, null=True)),
                ('last_active_date', models.DateTimeField(blank=True, null=True)),
                ('last_inactive_date', models.DateTimeField(blank=True, null=True)),
                ('inactive_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='client_branch.clientbranch')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.city')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='client.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.masterproduct')),
                ('services', models.ManyToManyField(blank=True, to='master_management.masterproductsubcategory')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.state')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_customers',
            },
        ),
    ]
