# Generated by Django 6.0.1 on 2026-01-31 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_customer', '0002_clientcustomer_geo_location_and_more'),
        ('master_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomer',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.mastergender'),
        ),
    ]
