# Generated by Django 6.0.1 on 2026-02-02 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_customer', '0003_alter_clientcustomer_gender'),
        ('master_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcustomeraddress',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.masterrelationship'),
        ),
    ]
