# Generated by Django 6.0.1 on 2026-02-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_customer', '0004_clientcustomeraddress_relation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcustomeraddress',
            name='area_locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
