# Generated by Django 6.0.1 on 2026-02-02 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_customer', '0005_clientcustomeraddress_area_locality'),
        ('test_package', '0004_alter_testpackage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomer',
            name='packages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_package.testpackage'),
        ),
        migrations.AlterField(
            model_name='clientcustomeraddress',
            name='address_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Office', 'Office'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
