# Generated by Django 6.0.1 on 2026-02-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_customer', '0006_alter_clientcustomer_packages_and_more'),
        ('test_package', '0004_alter_testpackage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcustomer',
            name='packages',
        ),
        migrations.AddField(
            model_name='clientcustomer',
            name='packages',
            field=models.ManyToManyField(blank=True, to='test_package.testpackage'),
        ),
    ]
