# Generated by Django 6.0.1 on 2026-02-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_customer', '0007_remove_clientcustomer_packages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcustomer',
            name='employee_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientcustomerdependent',
            name='dependent_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientcustomerdependent',
            name='member_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
