# Generated by Django 5.2.7 on 2026-01-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical_medical_master', '0002_branchzone_created_at_branchzone_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchZone',
        ),
    ]
