# Generated by Django 5.2.7 on 2026-01-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_medical_master', '0003_delete_branchzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseForMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
