# Generated by Django 6.0.1 on 2026-01-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical_medical_master', '0004_caseformaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generictest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='generictest',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='GenericTest',
        ),
    ]
