# Generated by Django 6.0.1 on 2026-01-28 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0009_alter_serviceprovider_client_company'),
        ('service_provider_master', '0003_accreditation_recognition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
