# Generated by Django 6.0.1 on 2026-02-06 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_management', '0004_rename_doctorlanguage_masterlanguage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lead_type', models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate')], default='Individual', max_length=20)),
                ('lead_owner', models.CharField(blank=True, max_length=255, null=True)),
                ('lead_source', models.CharField(choices=[('Online', 'Online'), ('Referral', 'Referral'), ('Cold Call', 'Cold Call'), ('Walk-in', 'Walk-in'), ('Email Campaign', 'Email Campaign'), ('Social Media', 'Social Media'), ('Other', 'Other')], default='Online', max_length=50)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address_1', models.TextField(blank=True, null=True)),
                ('address_2', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('website_name', models.URLField(blank=True, null=True)),
                ('no_of_employees', models.IntegerField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, choices=[('Health Care', 'Health Care'), ('Insurance', 'Insurance'), ('Others', 'Others')], max_length=50, null=True)),
                ('service_category', models.CharField(blank=True, choices=[('Consultation', 'Consultation'), ('Insurance Records', 'Insurance Records'), ('Diagnostics', 'Diagnostics'), ('Health Records', 'Health Records')], max_length=50, null=True)),
                ('renewal_care', models.BooleanField(default=False)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('policy_start_date', models.DateField(blank=True, null=True)),
                ('policy_end_date', models.DateField(blank=True, null=True)),
                ('receive_email', models.BooleanField(default=False)),
                ('receive_sms', models.BooleanField(default=False)),
                ('receive_whatsapp', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('upload_document', models.FileField(blank=True, null=True, upload_to='leads/documents/')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('existing_insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='master_management.masterinsurancecompany')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.mastergender')),
                ('lead_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='master_management.casestatus')),
                ('policy_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='master_management.mastertypeofinsurance')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_management.state')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
