# Generated by Django 6.0.1 on 2026-02-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0002_leadsource_alter_lead_lead_source_leadstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='policy_end_date',
            new_name='follow_up_date',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='policy_start_date',
            new_name='reminder_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='renewal_care',
        ),
        migrations.AddField(
            model_name='lead',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
