# Generated by Django 6.0.1 on 2026-02-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0004_individualclient_individualclientdependent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Leads'},
        ),
    ]
