# Generated by Django 6.0.1 on 2026-02-11 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0005_alter_lead_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualclient',
            name='upload_document',
        ),
        migrations.CreateModel(
            name='IndividualClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.FileField(upload_to='individual_clients/documents/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('individual_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='lead_management.individualclient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Individual Client Document',
                'verbose_name_plural': 'Individual Client Documents',
                'db_table': 'individual_client_documents',
            },
        ),
    ]
