# Generated by Django 6.0.1 on 2026-01-10 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('center_code', models.CharField(max_length=100, unique=True)),
                ('unique_name', models.CharField(max_length=255, unique=True)),
                ('token_id', models.CharField(blank=True, max_length=100, null=True)),
                ('provider_type', models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('standalonelab', 'Standalone Lab'), ('collectioncenter', 'Collection Center'), ('imagingcenter', 'Imaging Center')], max_length=50)),
                ('grade', models.CharField(choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Standard'), ('C', 'Grade C - Basic')], max_length=10)),
                ('vendor', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticBanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('gst_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnostic_center.diagnosticcenter')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mou_signed', models.BooleanField(default=False)),
                ('mou_signed_date', models.DateField(blank=True, null=True)),
                ('assigned_clients', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='diagnostic_center.diagnosticcenter')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nabl', models.BooleanField(default=False)),
                ('cap', models.BooleanField(default=False)),
                ('iso', models.BooleanField(default=False)),
                ('recognized_by', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnostic_center.diagnosticcenter')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticLabCapabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hematology', models.BooleanField(default=False)),
                ('biochemistry', models.BooleanField(default=False)),
                ('microbiology', models.BooleanField(default=False)),
                ('pathology', models.BooleanField(default=False)),
                ('serology', models.BooleanField(default=False)),
                ('histopathology', models.BooleanField(default=False)),
                ('endocrinology', models.BooleanField(default=False)),
                ('cytology', models.BooleanField(default=False)),
                ('immunology', models.BooleanField(default=False)),
                ('xray', models.BooleanField(default=False)),
                ('digital_xray', models.BooleanField(default=False)),
                ('ultrasound', models.BooleanField(default=False)),
                ('ct_scan', models.BooleanField(default=False)),
                ('mri', models.BooleanField(default=False)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnostic_center.diagnosticcenter')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True, null=True)),
                ('work_start', models.TimeField()),
                ('work_end', models.TimeField()),
                ('open_on_sunday', models.BooleanField(default=False)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='diagnostic_center.diagnosticcenter')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_collection', models.BooleanField(default=False)),
                ('home_collection_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_area', models.TextField(blank=True, null=True)),
                ('health_checkup', models.BooleanField(default=False)),
                ('parking_available', models.BooleanField(default=False)),
                ('home_delivery', models.BooleanField(default=False)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diagnostic_center.diagnosticcenter')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_staff', models.PositiveIntegerField(default=0)),
                ('doctor_consultants', models.PositiveIntegerField(default=0)),
                ('visiting_consultants', models.PositiveIntegerField(default=0)),
                ('ambulance_available', models.BooleanField(default=False)),
                ('bls_ambulance_count', models.PositiveIntegerField(default=0)),
                ('acls_ambulance_count', models.PositiveIntegerField(default=0)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='diagnostic_center.diagnosticcenter')),
            ],
        ),
    ]
