# Generated by Django 6.0.1 on 2026-01-10 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_center', '0002_diagnosticaccreditation_created_at_and_more'),
        ('location', '0002_alter_city_created_by_alter_city_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticlocation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_locations', to='location.city'),
        ),
    ]
