# Generated by Django 6.0.1 on 2026-01-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_center', '0003_alter_diagnosticlocation_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticaccreditation',
            name='iso_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='diagnosticlabcapabilities',
            name='_2d_echo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticlabcapabilities',
            name='color_doppler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticlabcapabilities',
            name='ecg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticlabcapabilities',
            name='fluoroscopy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticlabcapabilities',
            name='mammogram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticlabcapabilities',
            name='nuclear_imaging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticlabcapabilities',
            name='pet_scan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticlabcapabilities',
            name='pft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticlabcapabilities',
            name='tmt',
            field=models.BooleanField(default=False),
        ),
    ]
