# Generated by Django 6.0.1 on 2026-01-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_center', '0004_diagnosticaccreditation_iso_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticaccreditation',
            name='iso_type',
            field=models.CharField(max_length=100),
        ),
    ]
