# Generated by Django 6.0.1 on 2026-01-13 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic_center', '0005_alter_diagnosticaccreditation_iso_type'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticcenter',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_centers', to='vendors.vendor'),
        ),
    ]
